### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by BBoldt** [ThexXTURBOXx/balkons-weaponmod#27]
Fabric server, 1.21

https://gist.github.com/BBoldt/1c8b0123f42538b5ac381564ffacf8db

**Comment by ThexXTURBOXx** [comment]
There is always some oversight - thanks for the report!
I have fixed this now :)

**Comment by ThexXTURBOXx** [comment]
The commit that fixed this together with a few additional things is https://github.com/ThexXTURBOXx/Balkons-WeaponMod-Legacy/commit/cbeb3ff67088fdca9ec374452e7e693f9e3e7cb7
However, please be aware that there are still LOTS of bugs on Fabric server environments.
I have reported this to Architectury API accordingly (since I think its their fault: https://github.com/architectury/architectury-api/issues/523).
If it's not their fault, I will reopen this, though!

**Comment by ThexXTURBOXx** [comment]
I have fixed this issue on Architectury API's end - they forgot to properly register the `SpawnEntityPacket` on the server side (see https://github.com/architectury/architectury-api/pull/524).
However, I found two more small issues regarding 1.20.6 and 1.21 servers.
I have fixed them in the newest commit for both versions. Now, everything should be in order (hopefully)

P.S.: I have no idea when and if my fix will be published for Architectury API!
