### ISSUE TITLE
1.21 Issue with Blunderbuss Projectile

### ISSUE THREAD

**Issue by makumaku1974** [ThexXTURBOXx/balkons-weaponmod#30]
Behold! Shooting Stars!
![2024-06-25_19 38 56](https://github.com/ThexXTURBOXx/Balkons-WeaponMod-Legacy/assets/129804277/e5342bd5-c72d-467e-830b-9814e63fb0e8)

**Comment by ThexXTURBOXx** [comment]
Interesting... I had not noticed this before. Definetly a bug (only visual, though!), thanks for reporting! :)

**Comment by ThexXTURBOXx** [comment]
This was actually something from the original Balkon's WeaponMod: The blunderbuss shots left a tiny trail behind them.
At first, I fixed them, but then I noticed that they don't really look good anyway, so I decided to just comment the corresponding code out.
Hence, this is fixed in the next version!
