### ISSUE TITLE
No Recipes in 1.20.1

### ISSUE THREAD

**Issue by NoTap0425** [ThexXTURBOXx/balkons-weaponmod#46]
Started a world with this mod and a few other small ones. There are no recipes in Survival and I can't craft anything. Can try and find additional information

**Comment by ThexXTURBOXx** [comment]
Are you using Fabric or Forge? Do you have something like REI installed to view the recipes or are you expecting them to be in the recipe book?

**Comment by ThexXTURBOXx** [comment]
Stale issue

**Comment by Gydalf** [comment]
I have been having the same issue, 1.20.1 forge 1.22.3. If I run the mod on its own, the recipes are there. Adding in JEI I can see that there are some empty tags included in the recipes as I have attempted to show below:

![image](https://github.com/user-attachments/assets/b98ea423-9492-4e29-a180-1232601eab4e)

I have sinytra connector installed and I believe this is what is specifically causing the recipes to not show up. Otherwise, they show up but with the bugged tags.

I have tested adding a data pack to replace the recipes with versions without the fabric condition, and have found it works now.  Feel free to update the forge version to change the recipes to exclude the fabric condition if that is possible without screwing up the fabric version.

**Comment by ThexXTURBOXx** [comment]
I am a bit hesitant to do that actually as this would require me to split the data resources in the two sets Forge and Fabric again.
As it stands currently, a change in the data resources for either will result in the same change being applied in the other also and I would like it to stay this way for convention's sake.
If the bug really only occurs when Sinytra Connector is installed, the bug should probably be reported over there instead.

**Comment by Gydalf** [comment]
Yeahh that's why I included the qualifier at the end about if it was possible, I'll report it on sinytra and in the meantime once I've finished the data pack for all the recipes I'll put a link to it here, for anyone experiencing the same issue. Thanks!

**Comment by Gydalf** [comment]
Data pack for Forge:
https://drive.google.com/drive/folders/1JvkcHpuN8wzNjyHIUJ0SdRDlQKDj3R55?usp=sharing
