### ISSUE TITLE
1.16.5 server crash while in a large modpack

### ISSUE THREAD

**Issue by Sulferix** [ThexXTURBOXx/balkons-weaponmod#66]
i get the following crash when attempting to load into my world with this mod installed:
[crash-2024-08-19_23.56.26-server.txt](https://github.com/user-attachments/files/16669259/crash-2024-08-19_23.56.26-server.txt)

removing this mod solves the crash

**Comment by ThexXTURBOXx** [comment]
Compatibility issue with some Quarry mod. I will see if BWM: Legacy or that other mod is really at fault here.

**Comment by Sulferix** [comment]
hey man, you're an absolute legend, not only for bringing back this absolute gem of a mod, but also with the support. i dont think ive ever seen this kind of support for a mod. 

heres the link to the quarry mod in question in case you are still looking for it: https://www.curseforge.com/minecraft/mc-mods/additional-enchanted-miner

**Comment by ThexXTURBOXx** [comment]
I just looked into this a bit more. I am 95% positive that the real culprit is [RoadRunner](https://www.curseforge.com/minecraft/mc-mods/roadrunner).
More specifically, it is [this mixin](https://github.com/MaxNeedsSnacks/roadrunner/blob/1.16.x/forge/src/main/java/me/jellysquid/mods/lithium/mixin/entity/data_tracker/use_arrays/DataTrackerMixin.java) that is at fault.
I will report this over there to get this resolved :)

**Comment by ThexXTURBOXx** [comment]
Now depends only on https://github.com/MaxNeedsSnacks/roadrunner/pull/85

**Comment by embeddedt** [comment]
This is fixed in RoadRunner 1.5.2
